remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #

title: "Roche Computational Sciences Summer School 2026"
description: "A Summer Week of Hand-on Computational Research in Drug Discovery"

show_downloads: false

