remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #

title: "Roche PMDA Summer CodeWeek 2024"
description: "Hand-on Modeling and Analytics in Drug Discovery For a Summer Week"

show_downloads: false

